# Webpacks and then Deploys to GitHub Pages
name: Build Unity WebGL And Deploy To Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # - name: Setup Pages
      #   uses: actions/configure-pages@v5

      - name: Install Unity CLI
        run: |-
          curl -fsSL https://public-cdn.cloud.unity3d.com/hub/prod/cli/install.sh | UNITY_CLI_CHANNEL=beta bash
          export PATH="$PATH:~/.unity/bin"
          unity --version

      - name: Install Editor/Modules
        run: |-
          export PATH="$PATH:~/.unity/bin"
          #Set Unity version below
          # unity install 6.3 -m webgl

      - name: Install Editor Dependences
        run: |-
          sudo apt-get update
          sudo apt-get install libgtk-3-dev libxrandr2 libxcursor1 libgl1
      
      - name: Build
        run: |-
          export PATH="$PATH:~/.unity/bin"
          unity --version
        
      # - name: Upload artifact
      #   uses: actions/upload-pages-artifact@v3
      #   with:
      #     # Upload entire repository
      #     path: dist
      # - name: Deploy to GitHub Pages
      #   id: deployment
      #   uses: actions/deploy-pages@v5
